-- Drop existing constraints
-- Drop constraints from RendezVous table
DECLARE
  v_constraint_name VARCHAR2(100);
BEGIN
  FOR c IN (SELECT constraint_name FROM user_constraints WHERE table_name = 'RENDEZVOUS') LOOP
    v_constraint_name := c.constraint_name;
    EXECUTE IMMEDIATE 'ALTER TABLE RendezVous DROP CONSTRAINT ' || v_constraint_name;
  END LOOP;
END;
/

-- Drop constraints from Consultation table
DECLARE
  v_constraint_name VARCHAR2(100);
BEGIN
  FOR c IN (SELECT constraint_name FROM user_constraints WHERE table_name = 'CONSULTATION') LOOP
    v_constraint_name := c.constraint_name;
    EXECUTE IMMEDIATE 'ALTER TABLE Consultation DROP CONSTRAINT ' || v_constraint_name;
  END LOOP;
END;
/

-- Drop constraints from DossierMedicale table
DECLARE
  v_constraint_name VARCHAR2(100);
BEGIN
  FOR c IN (SELECT constraint_name FROM user_constraints WHERE table_name = 'DOSSIERMEDICALE') LOOP
    v_constraint_name := c.constraint_name;
    EXECUTE IMMEDIATE 'ALTER TABLE DossierMedicale DROP CONSTRAINT ' || v_constraint_name;
  END LOOP;
END;
/

-- Drop constraints from Patient table
DECLARE
  v_constraint_name VARCHAR2(100);
BEGIN
  FOR c IN (SELECT constraint_name FROM user_constraints WHERE table_name = 'PATIENT') LOOP
    v_constraint_name := c.constraint_name;
    EXECUTE IMMEDIATE 'ALTER TABLE Patient DROP CONSTRAINT ' || v_constraint_name;
  END LOOP;
END;
/

-- Drop constraints from Medecin table
DECLARE
  v_constraint_name VARCHAR2(100);
BEGIN
  FOR c IN (SELECT constraint_name FROM user_constraints WHERE table_name = 'MEDECIN') LOOP
    v_constraint_name := c.constraint_name;
    EXECUTE IMMEDIATE 'ALTER TABLE Medecin DROP CONSTRAINT ' || v_constraint_name;
  END LOOP;
END;
/

-- Drop constraints from SessionCompte table
DECLARE
  v_constraint_name VARCHAR2(100);
BEGIN
  FOR c IN (SELECT constraint_name FROM user_constraints WHERE table_name = 'SESSIONCOMPTE') LOOP
    v_constraint_name := c.constraint_name;
    EXECUTE IMMEDIATE 'ALTER TABLE SessionCompte DROP CONSTRAINT ' || v_constraint_name;
  END LOOP;
END;
/


-- Drop existing sequences
DROP SEQUENCE numDos_seq;
DROP SEQUENCE numCons_seq;
DROP SEQUENCE numRen_seq;
DROP SEQUENCE numSesCom_seq;
DROP SEQUENCE matPat_seq;

-- Drop existing tables
DROP TABLE SessionCompte CASCADE CONSTRAINTS;
DROP TABLE RendezVous CASCADE CONSTRAINTS;
DROP TABLE Consultation CASCADE CONSTRAINTS;
DROP TABLE Medecin CASCADE CONSTRAINTS;
DROP TABLE Patient CASCADE CONSTRAINTS;
DROP TABLE DossierMedicale CASCADE CONSTRAINTS;

-- Create sequences
CREATE SEQUENCE numDos_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE numCons_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE numRen_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE numSesCom_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE matPat_seq START WITH 1 INCREMENT BY 1;

-- Create tables
CREATE TABLE Patient (
    matPat VARCHAR2(10) PRIMARY KEY,
    nom VARCHAR2(50),
    prenom VARCHAR2(50),
    email VARCHAR2(100),
    gender VARCHAR2(1),
    maladies VARCHAR2(200),
    adresse VARCHAR2(100),
    numtel VARCHAR2(20),
    birthdate DATE
);

CREATE TABLE Medecin (
    medStat VARCHAR2(1) PRIMARY KEY,
    nom VARCHAR2(50),
    prenom VARCHAR2(50),
    status VARCHAR2(50),
    CONSTRAINT chk_medStat CHECK (medStat IN ('P', 'R'))
);

CREATE TABLE RendezVous (
    numRen NUMBER PRIMARY KEY,
    dateRen DATE,
    heure VARCHAR2(10),
    matPat_Ren VARCHAR2(10),
    medStat_Ren VARCHAR2(1),
    FOREIGN KEY (matPat_Ren) REFERENCES Patient(matPat) ON DELETE CASCADE,
    FOREIGN KEY (medStat_Ren) REFERENCES Medecin(medStat)
);

CREATE TABLE Consultation (
    numCons NUMBER PRIMARY KEY,
    diagnostic VARCHAR2(200),
    dateCons DATE,
    medicament VARCHAR2(100),
    matPat_Dos VARCHAR2(10),
    FOREIGN KEY (matPat_Dos) REFERENCES Patient(matPat) ON DELETE CASCADE
);

CREATE TABLE DossierMedicale (
    numDos NUMBER PRIMARY KEY,
    groupeSanguin VARCHAR2(5),
    matPat_Dos VARCHAR2(10),
    FOREIGN KEY (matPat_Dos) REFERENCES Patient(matPat) ON DELETE CASCADE
);

CREATE TABLE SessionCompte (
    numSesCom NUMBER PRIMARY KEY,
    utilisateur VARCHAR2(50),
    motDePasse VARCHAR2(100),
    matPat_SesCom VARCHAR2(10),
    FOREIGN KEY (matPat_SesCom) REFERENCES Patient(matPat) ON DELETE CASCADE
);

-- Create trigger for Patient table auto-increment
CREATE OR REPLACE TRIGGER matPat_trigger
BEFORE INSERT ON Patient
FOR EACH ROW
BEGIN
    SELECT matPat_seq.nextval INTO :new.matPat FROM dual;
END;
/

-- Insert initial data into Medecin table
INSERT INTO Medecin (medStat, nom, prenom, status) VALUES ('P', 'Nom_Principal', 'Prenom_Principal', 'Médecin Principal');
INSERT INTO Medecin (medStat, nom, prenom, status) VALUES ('R', 'Nom_Remplacant', 'Prenom_Remplacant', 'Médecin Remplaçant');

-- Commit the transaction
COMMIT;

-- Inserts generated by chat gpt
-- Insert data for Patient to tast
INSERT INTO Patient (nom, prenom, email, gender, maladies, adresse, numtel, birthdate) 
VALUES ('Doe', 'John', 'john.doe@example.com', 'M', 'Hypertension', '123 Main St, City', '1234567890', TO_DATE('1990-01-01', 'YYYY-MM-DD'));

INSERT INTO Patient (nom, prenom, email, gender, maladies, adresse, numtel, birthdate) 
VALUES ('Smith', 'Emma', 'emma.smith@example.com', 'F', 'Asthma', '456 Oak Ave, Town', '9876543210', TO_DATE('1985-05-15', 'YYYY-MM-DD'));

INSERT INTO Patient (nom, prenom, email, gender, maladies, adresse, numtel, birthdate) 
VALUES ('Johnson', 'Michael', 'michael.johnson@example.com', 'M', 'Diabetes', '789 Pine Rd, Village', '5551234567', TO_DATE('1978-10-20', 'YYYY-MM-DD'));

INSERT INTO Patient (nom, prenom, email, gender, maladies, adresse, numtel, birthdate) 
VALUES ('Brown', 'Sarah', 'sarah.brown@example.com', 'F', 'Migraine', '101 Elm St, Rural', '3219876543', TO_DATE('1982-03-12', 'YYYY-MM-DD'));

INSERT INTO Patient (nom, prenom, email, gender, maladies, adresse, numtel, birthdate) 
VALUES ('Wilson', 'David', 'david.wilson@example.com', 'M', 'Arthritis', '222 Maple Ave, Suburb', '9998887777', TO_DATE('1970-07-28', 'YYYY-MM-DD'));

-- Insert data for Medical Files (DossierMedicale)
INSERT INTO DossierMedicale (numDos, groupeSanguin, matPat_Dos) VALUES (numDos_seq.nextval, 'A+', (SELECT matPat FROM Patient WHERE nom = 'Doe' AND prenom = 'John'));
INSERT INTO DossierMedicale (numDos, groupeSanguin, matPat_Dos) VALUES (numDos_seq.nextval, 'B-', (SELECT matPat FROM Patient WHERE nom = 'Smith' AND prenom = 'Emma'));
INSERT INTO DossierMedicale (numDos, groupeSanguin, matPat_Dos) VALUES (numDos_seq.nextval, 'O+', (SELECT matPat FROM Patient WHERE nom = 'Johnson' AND prenom = 'Michael'));
INSERT INTO DossierMedicale (numDos, groupeSanguin, matPat_Dos) VALUES (numDos_seq.nextval, 'AB+', (SELECT matPat FROM Patient WHERE nom = 'Brown' AND prenom = 'Sarah'));
INSERT INTO DossierMedicale (numDos, groupeSanguin, matPat_Dos) VALUES (numDos_seq.nextval, 'A-', (SELECT matPat FROM Patient WHERE nom = 'Wilson' AND prenom = 'David'));

-- Insert data for Consultations
INSERT INTO Consultation (numCons, diagnostic, dateCons, medicament, matPat_Dos) VALUES (numCons_seq.nextval, 'High blood pressure', TO_DATE('2024-05-10', 'YYYY-MM-DD'), 'Lisinopril', (SELECT matPat FROM Patient WHERE nom = 'Doe' AND prenom = 'John'));
INSERT INTO Consultation (numCons, diagnostic, dateCons, medicament, matPat_Dos) VALUES (numCons_seq.nextval, 'Asthma attack', TO_DATE('2024-05-08', 'YYYY-MM-DD'), 'Albuterol', (SELECT matPat FROM Patient WHERE nom = 'Smith' AND prenom = 'Emma'));
INSERT INTO Consultation (numCons, diagnostic, dateCons, medicament, matPat_Dos) VALUES (numCons_seq.nextval, 'Blood sugar control', TO_DATE('2024-05-09', 'YYYY-MM-DD'), 'Insulin', (SELECT matPat FROM Patient WHERE nom = 'Johnson' AND prenom = 'Michael'));
INSERT INTO Consultation (numCons, diagnostic, dateCons, medicament, matPat_Dos) VALUES (numCons_seq.nextval, 'Migraine headache', TO_DATE('2024-05-11', 'YYYY-MM-DD'), 'Sumatriptan', (SELECT matPat FROM Patient WHERE nom = 'Brown' AND prenom = 'Sarah'));
INSERT INTO Consultation (numCons, diagnostic, dateCons, medicament, matPat_Dos) VALUES (numCons_seq.nextval, 'Joint pain', TO_DATE('2024-05-07', 'YYYY-MM-DD'), 'Ibuprofen', (SELECT matPat FROM Patient WHERE nom = 'Wilson' AND prenom = 'David'));

-- Insert data for Appointments (RendezVous)
INSERT INTO RendezVous (numRen, dateRen, heure, matPat_Ren, medStat_Ren) VALUES (numRen_seq.nextval, TO_DATE('2024-05-15', 'YYYY-MM-DD'), '10:00', (SELECT matPat FROM Patient WHERE nom = 'Doe' AND prenom = 'John'), 'P');
INSERT INTO RendezVous (numRen, dateRen, heure, matPat_Ren, medStat_Ren) VALUES (numRen_seq.nextval, TO_DATE('2024-05-16', 'YYYY-MM-DD'), '11:30', (SELECT matPat FROM Patient WHERE nom = 'Smith' AND prenom = 'Emma'), 'P');
INSERT INTO RendezVous (numRen, dateRen, heure, matPat_Ren, medStat_Ren) VALUES (numRen_seq.nextval, TO_DATE('2024-05-17', 'YYYY-MM-DD'), '09:45', (SELECT matPat FROM Patient WHERE nom = 'Johnson' AND prenom = 'Michael'), 'R');
INSERT INTO RendezVous (numRen, dateRen, heure, matPat_Ren, medStat_Ren) VALUES (numRen_seq.nextval, TO_DATE('2024-05-18', 'YYYY-MM-DD'), '13:15', (SELECT matPat FROM Patient WHERE nom = 'Brown' AND prenom = 'Sarah'), 'R');
INSERT INTO RendezVous (numRen, dateRen, heure, matPat_Ren, medStat_Ren) VALUES (numRen_seq.nextval, TO_DATE('2024-05-19', 'YYYY-MM-DD'), '15:00', (SELECT matPat FROM Patient WHERE nom = 'Wilson' AND prenom = 'David'), 'P');

-- Insert data for SessionCompte (User Accounts)
INSERT INTO SessionCompte (numSesCom, utilisateur, motDePasse, matPat_SesCom) VALUES (numSesCom_seq.nextval, 'john_doe', 'password123', (SELECT matPat FROM Patient WHERE nom = 'Doe' AND prenom = 'John'));
INSERT INTO SessionCompte (numSesCom, utilisateur, motDePasse, matPat_SesCom) VALUES (numSesCom_seq.nextval, 'emma_smith', 'password456', (SELECT matPat FROM Patient WHERE nom = 'Smith' AND prenom = 'Emma'));
INSERT INTO SessionCompte (numSesCom, utilisateur, motDePasse, matPat_SesCom) VALUES (numSesCom_seq.nextval, 'michael_johnson', 'password789', (SELECT matPat FROM Patient WHERE nom = 'Johnson' AND prenom = 'Michael'));
INSERT INTO SessionCompte (numSesCom, utilisateur, motDePasse, matPat_SesCom) VALUES (numSesCom_seq.nextval, 'sarah_brown', 'passwordABC', (SELECT matPat FROM Patient WHERE nom = 'Brown' AND prenom = 'Sarah'));
INSERT INTO SessionCompte (numSesCom, utilisateur, motDePasse, matPat_SesCom) VALUES (numSesCom_seq.nextval, 'david_wilson', 'passwordXYZ', (SELECT matPat FROM Patient WHERE nom = 'Wilson' AND prenom = 'David'));

-- Commit the transaction
COMMIT;
